using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Server.AppHost.Migrations
{
    /// <inheritdoc />
    public partial class CreateMissingTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Sessions') THEN
                CREATE TABLE public.""Sessions"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""StartTime"" timestamp with time zone NOT NULL,
                    ""EndTime"" timestamp with time zone,
                    ""Name"" character varying(256) NOT NULL,
                    CONSTRAINT ""PK_Sessions"" PRIMARY KEY (""Id"")
                );
            END IF;
            
            IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Packets') THEN
                CREATE TABLE public.""Packets"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""Crc16"" integer NOT NULL,
                    ""PacketCounter"" integer NOT NULL,
                    ""Payload"" double precision NOT NULL,
                    ""SyncMarker"" integer NOT NULL,
                    ""Timestamp"" double precision NOT NULL,
                    ""SessionId"" bigint NOT NULL,
                    CONSTRAINT ""PK_Packets"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_Packets_Sessions_SessionId"" FOREIGN KEY (""SessionId"") 
                        REFERENCES public.""Sessions"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_Packets_SessionId"" ON public.""Packets"" (""SessionId"");
            END IF;
            
            -- Добавляем записи о всех примененных миграциях
            IF NOT EXISTS (SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20250526153247_InitialCreate') THEN
                INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"")
                VALUES ('20250526153247_InitialCreate', '9.0.5');
            END IF;
            
            IF NOT EXISTS (SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20250526191909_UpdateDataTypes') THEN
                INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"")
                VALUES ('20250526191909_UpdateDataTypes', '9.0.5');
            END IF;
        END $$;
    ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
