// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Data;

#nullable disable

namespace Server.AppHost.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250517180727_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.TelemetryPacket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Crc16")
                        .HasColumnType("smallint");

                    b.Property<long>("PacketCounter")
                        .HasColumnType("bigint");

                    b.Property<double>("Payload")
                        .HasColumnType("double precision");

                    b.Property<long>("SyncMarker")
                        .HasColumnType("bigint");

                    b.Property<double>("Timestamp")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Packets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
